 export const URLS = {
    home:"/",
    createPost:"/createPost",
    contact:"/contact",
    register:"/register",
    login:"/login",
    viewPost:(_id:string)=>`/post/${_id}`,
}


// const URLS = {
//   bookedClasses: "/booked-products",
//   visits: "/visits",
//   classes: "/classes",
//   experts: "/experts",
//   viewBookedClassesRoute: "/booked-classes/:id",
//   bookedServices: "/booked-services",
//   workoutCentral: "/workout-central",
//   calendar: "/calendar",
//   classesTypes: "/classes-types",
//   instructors: "/instructors",
//   documents: "/documents",
//   userAgreement: "/user-agreement",
//   selectedGym: "/selected-gym",
//   home: "/",
//   register: "/register",
//   revenue: "/revenue",
//   revenueDetails: "/revenue/:id",
//   visitsLog: "/visits-log",
//   invoices: "/invoices",
//   profile: "/profile",
//   accessDenied: "/access-denied",
//   staffLongueScreen: "/staff-longue-screen",
//   longueInformationManagement: "/longue-information-management",
//   users: "/employees",
//   usersTable: "/users-table",
//   overview: "/overview",
//   branches: "/branches",
//   notfound: "/404",
//   reports: "/reports",
//   reviews: "/reviews",
//   keywords: "/keywords",
//   inquiries: "/inquiries",
//   login: "/login",
//   resetPassword: "/reset-password",
//   verifyPassword: "/verify-Password",
//   forgotPassword: "/forgot-password",
//   admin: "/administrators",
//   aboutUs: "/about-us",
// };

// export default URLS;